services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - "5552:5552"
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_ERLANG_COOKIE=secretcookie
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
        volumes:
            - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"